name: core-infra

trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
- template: variables/dev.yml

stages:
- stage:
  displayName: Dev
  jobs:
    - job:
      displayName: Development
      steps:
        - checkout: self
          clean: true

        - task: AzureCLI@1
          displayName: "Deploy - Infra"
          name: "Create_Infra"
          inputs:
            azureSubscription: $(serviceConnectionName)
            scriptLocation: "inlineScript"
            inlineScript: |
              az deployment group create \
              --name core-deployment \
              --resource-group $(resourceGroupName) \
              --template-file "$(System.DefaultWorkingDirectory)/templates/main.bicep" \
              --parameters "$(System.DefaultWorkingDirectory)/parameters/infra.dev.json" \
              --verbose